name: board_game_borrower
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - Assets/
    - Assets/logo-red.png

  fonts:
    - family: Marujo
      fonts:
        - asset: Assets/Fonts/Marujo/Marujo.ttf
    - family: worksans
      fonts:
        - asset: Assets/Fonts/worksans/WorkSans-Regular.ttf
        - asset: Assets/Fonts/worksans/WorkSans-Bold.ttf
          weight: 700
